baseURL = "https://aca-cse-iitk.github.io"
title = "ACA"
author = "Jaskirat Singh"
paginate = 3
theme = "BluestNight"
contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"
canonifyurls = true


[outputs]
    home = ["HTML", "CSS", "JSON", "RSS"]

[Params]
    tagline = "Association of Computing Activities"
    description = "Association of Computing activities" # Description of your site
    authorbox = true
    author = "ACA"
    post_navigation = true
    alert = "SUMMER SCHOOL registration: link -------> https://summerschool.cse.iitk.ac.in/index.php"
    favicon = "/favicon.jpg"

[Params.widgets]
    search = false
    recent_articles = true
    categories = true
    tags = true
    drafts = true
    tags_counter = false

[menu]
    [[menu.main]]
        name = "Home"
        weight = 2
        url = "/"
    [[menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects"
[Params.social]
    facebook = "aca.cse.iitk"
